language: groovy

jdk:
  - oraclejdk7
  - oraclejdk8

addons:
  postgresql: "9.3"

services:
  - postgresql

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - bash pg_setup.sh
  - ./gradlew cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)