language: groovy

jdk:
  - oraclejdk7
  - oraclejdk8

addons:
  postgresql: "9.3"

services:
  - postgresql

before_install: ./pg_setup.sh

script: mvn cobertura:cobertura-integration-test -Dcobertura.report.format=xml

after_success:
  - bash <(curl -s https://codecov.io/bash)