language: groovy

jdk:
  - oraclejdk7
  - oraclejdk8

addons:
  postgresql: "9.3"

services:
  - postgresql

script:
  - bash pg_setup.sh
  - ./gradlew cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)