language: groovy

jdk:
  - oraclejdk7
  - oraclejdk8

addons:
  postgresql: "9.3"

services:
  - postgresql

script:
  - ./pg_setup.sh
  - mvn cobertura:cobertura-integration-test -Dcobertura.report.format=xml

after_success:
  - bash <(curl -s https://codecov.io/bash)